GET http://localhost:5000/users

###
GET http://localhost:5000/settingweb

###
GET http://localhost:5000/tipe

###
GET http://localhost:5000/kategori

###
GET http://localhost:5000/kategori/mobile-legends

###
GET http://localhost:5000/kategori/populer

###
GET http://localhost:5000/kategoribytipe

###
GET http://localhost:5000/kategori/services

###
GET http://localhost:5000/kategoriforadmin?page=1&limit=5

###
GET http://localhost:5000/layanan

###
POST http://localhost:5000/layanan/price
Content-Type: application/json

{
    "nominal": 3763
}

###
GET http://localhost:5000/berita/swiper

###
GET http://localhost:5000/pembelianforcektransaksi

###
GET http://localhost:5000/pembelianfordashboardadmin

###
GET http://localhost:5000/pembelianforsemuapesananadmin

###
GET http://localhost:5000/pembelian

###
GET http://localhost:5000/method

###
GET http://localhost:5000/rating

###
GET http://localhost:5000/rating/mobile-legends

###
//Add User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "testadmin",
    "username": "testadmin",
    "password": "testadmin",
    "whatsapp": "080808808"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "testadmin",
    "password": "testadmin"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout